import PDFDocument from 'pdfkit';
// @ts-ignore — json2csv has no type declarations
import { Parser } from 'json2csv';
import { pool } from '../../config/database';
import * as portfolioService from '../portfolio/portfolio.service';
import { formatRupiah } from '../../utils/stockHelper';

export const generatePortfolioPDF = async (portfolioId: number): Promise<Buffer> => {
  const summary = await portfolioService.getPortfolioSummary(portfolioId);
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const buffers: Buffer[] = [];
  
  return new Promise((resolve, reject) => {
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Title
    doc.fontSize(20).text('Laporan Portofolio — Asisten+Stock AI', { align: 'center' });
    doc.moveDown();
    
    // Date
    doc.fontSize(12).text(`Tanggal Dibuat: ${new Date().toLocaleDateString('id-ID')}`, { align: 'center' });
    doc.moveDown(2);

    // Portfolio Summary
    doc.fontSize(14).text('Ringkasan Portofolio', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12)
       .text(`Total Net Worth: ${formatRupiah(summary.total_net_worth || 0)}`)
       .text(`Total Diinvestasikan: ${formatRupiah(summary.total_invested || 0)}`)
       .text(`Floating P/L: ${formatRupiah(summary.total_floating_pnl || 0)}`)
       .text(`P/L %: ${(summary.total_floating_pnl_percent || 0).toFixed(2)}%`);
    doc.moveDown(2);

    // Table of Holdings
    doc.fontSize(14).text('Daftar Aset', { underline: true });
    doc.moveDown(0.5);
    
    if (summary.holdings && summary.holdings.length > 0) {
      summary.holdings.forEach((h: any, i: number) => {
        doc.fontSize(10).text(`${i + 1}. Ticker: ${h.ticker} | Tipe: ${h.asset_type} | Qty: ${h.quantity} | Avg: ${formatRupiah(h.avg_buy_price || 0)} | Curr: ${formatRupiah(h.current_price || 0)} | Value: ${formatRupiah(h.market_value_idr || 0)} | P/L: ${formatRupiah(h.floating_pnl || 0)} (${(h.floating_pnl_percent || 0).toFixed(2)}%) | Weight: ${(h.weight_percent || 0).toFixed(2)}%`);
        doc.moveDown(0.5);
      });
    } else {
      doc.fontSize(10).text('Tidak ada aset.');
    }
    
    doc.moveDown(2);

    // Asset allocation breakdown
    doc.fontSize(14).text('Alokasi Aset', { underline: true });
    doc.moveDown(0.5);
    const allocations = (summary as any).asset_allocations || (summary as any).asset_allocation;
    if (allocations) {
       Object.entries(allocations).forEach(([type, alloc]: [string, any]) => {
           doc.fontSize(10).text(`- ${type}: ${formatRupiah(alloc.value || 0)} (${(alloc.percentage || 0).toFixed(2)}%)`);
       });
    } else {
        doc.fontSize(10).text('Tidak ada alokasi.');
    }

    doc.moveDown(3);
    
    // Footer
    doc.fontSize(10).text('Generated by Asisten+Stock AI', { align: 'center' });

    doc.end();
  });
};

export const generateTransactionCSV = async (portfolioId: number, dateFrom?: string, dateTo?: string): Promise<string> => {
  let query = `SELECT transaction_date, ticker, asset_type, action, quantity, price, total_amount, currency, notes FROM stock_transactions WHERE portfolio_id = $1`;
  const params: any[] = [portfolioId];
  let paramIdx = 2;

  if (dateFrom) {
    query += ` AND transaction_date >= $${paramIdx}`;
    params.push(dateFrom);
    paramIdx++;
  }
  
  if (dateTo) {
    query += ` AND transaction_date <= $${paramIdx}`;
    params.push(dateTo);
    paramIdx++;
  }

  query += ` ORDER BY transaction_date DESC`;

  const result = await pool.query(query, params);
  
  const mappedData = result.rows.map((row) => ({
    "Tanggal": new Date(row.transaction_date).toLocaleDateString('id-ID'),
    "Ticker": row.ticker,
    "Tipe Aset": row.asset_type,
    "Aksi (BUY/SELL)": row.action,
    "Kuantitas": row.quantity,
    "Harga Satuan": row.price,
    "Total Nominal": row.total_amount,
    "Mata Uang": row.currency,
    "Catatan": row.notes || ""
  }));

  if (mappedData.length === 0) {
    return "Tanggal,Ticker,Tipe Aset,Aksi (BUY/SELL),Kuantitas,Harga Satuan,Total Nominal,Mata Uang,Catatan\n";
  }

  const parser = new Parser();
  const csv = parser.parse(mappedData);
  return csv;
};

export const generateTaxReportPDF = async (portfolioId: number, year?: number): Promise<Buffer> => {
  const taxSummary = await portfolioService.getPortfolioTaxSummary(portfolioId);
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const buffers: Buffer[] = [];
  
  return new Promise((resolve, reject) => {
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    doc.fontSize(20).text('Laporan Simulasi Pajak Investasi — Asisten+Stock AI', { align: 'center' });
    doc.moveDown();
    
    doc.fontSize(12).text(`Tanggal Dibuat: ${new Date().toLocaleDateString('id-ID')}`, { align: 'center' });
    if (year) {
      doc.text(`Tahun Pajak: ${year}`, { align: 'center' });
    }
    doc.moveDown(2);

    doc.fontSize(14).text('Ringkasan Pajak', { underline: true });
    doc.moveDown(0.5);
    
    doc.fontSize(12).text(`Total Unrealized PNL: ${formatRupiah(taxSummary.total_unrealized_pnl_idr || 0)}`);
       
    const totalPotentialTax = taxSummary.annual_spt_summary?.total_estimated_tax_if_realized_idr || 0;
    doc.text(`Total Potensi Pajak (jika direalisasikan): ${formatRupiah(totalPotentialTax)}`);
    doc.moveDown(2);

    doc.fontSize(14).text('Rincian Pajak Per Aset', { underline: true });
    doc.moveDown(0.5);
    
    if (taxSummary.holdings_tax_breakdown && taxSummary.holdings_tax_breakdown.length > 0) {
      taxSummary.holdings_tax_breakdown.forEach((h: any, i: number) => {
        doc.fontSize(10).text(`${i + 1}. ${h.ticker} (${h.asset_type}) | P/L: ${formatRupiah(h.floating_pnl_idr || 0)} | Potensi Pajak: ${formatRupiah(h.potential_exit_tax_idr || 0)}`);
        doc.text(`   Aturan: ${h.tax_rule}`);
        doc.moveDown(0.5);
      });
    } else {
      doc.fontSize(10).text('Tidak ada aset.');
    }
    
    doc.moveDown(2);
    
    doc.fontSize(14).text('Kode Pelaporan SPT Tahunan', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10)
       .text('- Crypto: 039 - Investasi Lainnya / Aset Kripto')
       .text('- Saham IDX: 031 - Saham')
       .text('- ETF/Saham Global: 035 - Investasi Luar Negeri')
       .text('- Emas: 021 - Logam Mulia');
    
    doc.moveDown(3);
    doc.fontSize(10).text('Disclaimer: Ini adalah simulasi. Konsultasikan dengan konsultan pajak profesional.', { align: 'center', oblique: true });

    doc.end();
  });
};
