import * as portfolioService from "./portfolio.service";

export type StressScenarioType =
  | "market_crash_30"
  | "crypto_winter_60"
  | "stagflation_recession"
  | "idr_depreciation_20"
  | "custom";

export interface StressScenarioConfig {
  name: string;
  description: string;
  shocks: {
    stock: number;   // e.g. -0.30 for -30%
    crypto: number;  // e.g. -0.50
    gold: number;    // e.g. +0.15
    etf: number;     // e.g. -0.25
    cash: number;    // 0
  };
}

export const PRESET_SCENARIOS: Record<string, StressScenarioConfig> = {
  market_crash_30: {
    name: "Black Swan / Global Stock Crash -30%",
    description: "Skenario krisis likuiditas global mirip 2008 atau Maret 2020. Saham & ETF anjlok tajam, Crypto mengalami aksi jual masif, Emas berfungsi sebagai safe-haven.",
    shocks: {
      stock: -0.30,
      etf: -0.25,
      crypto: -0.50,
      gold: 0.15,
      cash: 0,
    },
  },
  crypto_winter_60: {
    name: "Crypto Winter -60%",
    description: "Skenario siklus bear market kripto parah. Aset kripto drop 60%, sedangkan pasar saham dan emas relatif stabil.",
    shocks: {
      stock: -0.05,
      etf: -0.03,
      crypto: -0.60,
      gold: 0.05,
      cash: 0,
    },
  },
  stagflation_recession: {
    name: "Stagflasi & Resesi Global",
    description: "Inflasi tinggi persisten diiringi suku bunga tinggi. Valuasi saham tertekan, namun komoditas dan emas menguat signifikan.",
    shocks: {
      stock: -0.20,
      etf: -0.15,
      crypto: -0.35,
      gold: 0.25,
      cash: -0.05,
    },
  },
  idr_depreciation_20: {
    name: "Depresiasi Rupiah -20% (USD Menguat)",
    description: "Rupiah melemah tajam terhadap USD. Aset berdenominasi USD (VT, USDT, Emas) memperoleh keuntungan selisih kurs, sementara saham domestik tertekan.",
    shocks: {
      stock: -0.12,
      etf: 0.18, // USD denominated gain
      crypto: 0.20, // USD denominated gain
      gold: 0.22,
      cash: 0,
    },
  },
};

export interface AssetStressResult {
  ticker: string;
  asset_type: string;
  initial_value_idr: number;
  shock_percent: number;
  stressed_value_idr: number;
  delta_idr: number;
}

export interface StressTestReport {
  scenario_key: string;
  scenario_name: string;
  scenario_description: string;
  initial_portfolio_value: number;
  stressed_portfolio_value: number;
  total_loss_idr: number;
  drawdown_percent: number;
  resilience_rating: "Kuat (Tahan Banting)" | "Moderat (Waspada)" | "Rentan (Perlu Lindung Nilai)";
  safe_haven_buffer_idr: number; // profit generated by hedging assets
  worst_hit_assets: AssetStressResult[];
  holdings_breakdown: AssetStressResult[];
  strategic_recommendations: string[];
}

export const runPortfolioStressTest = async (
  portfolioId: number = 1,
  scenarioKey: StressScenarioType = "market_crash_30",
  customShocks?: Partial<StressScenarioConfig["shocks"]>
): Promise<StressTestReport> => {
  const summary = await portfolioService.getPortfolioSummary(portfolioId);
  const scenario = PRESET_SCENARIOS[scenarioKey] || PRESET_SCENARIOS.market_crash_30;

  const shocks = {
    ...scenario.shocks,
    ...(customShocks || {}),
  };

  const initialTotal = summary.total_net_worth || 0;
  let stressedTotal = 0;
  let safeHavenBuffer = 0;

  const breakdown: AssetStressResult[] = (summary.holdings || []).map((h: any) => {
    const val = Number(h.market_value_idr || 0);
    const type = (h.asset_type || "STOCK").toUpperCase();

    let shock = 0;
    if (type.includes("CRYPTO")) shock = shocks.crypto;
    else if (type.includes("GOLD") || type.includes("EMAS")) shock = shocks.gold;
    else if (type.includes("ETF")) shock = shocks.etf;
    else shock = shocks.stock;

    const stressedVal = Math.max(0, val * (1 + shock));
    const delta = stressedVal - val;

    if (delta > 0) {
      safeHavenBuffer += delta;
    }

    stressedTotal += stressedVal;

    return {
      ticker: h.ticker,
      asset_type: type,
      initial_value_idr: Math.round(val),
      shock_percent: Number((shock * 100).toFixed(1)),
      stressed_value_idr: Math.round(stressedVal),
      delta_idr: Math.round(delta),
    };
  });

  // Include cash
  const cash = Number(summary.cash_balance || 0);
  const cashStressed = cash * (1 + (shocks.cash || 0));
  stressedTotal += cashStressed;

  const totalDelta = stressedTotal - initialTotal;
  const drawdownPct = initialTotal > 0 ? (totalDelta / initialTotal) * 100 : 0;

  // Sort worst hit assets
  const worstHit = [...breakdown]
    .sort((a, b) => a.delta_idr - b.delta_idr)
    .slice(0, 3);

  // Determine resilience
  let resilience: "Kuat (Tahan Banting)" | "Moderat (Waspada)" | "Rentan (Perlu Lindung Nilai)" = "Moderat (Waspada)";
  const recommendations: string[] = [];

  if (drawdownPct > -15) {
    resilience = "Kuat (Tahan Banting)";
    recommendations.push("Portofolio memiliki bauran aset defensif yang baik sehingga tahan guncangan krisis.");
  } else if (drawdownPct > -30) {
    resilience = "Moderat (Waspada)";
    recommendations.push("Penurunan cukup terasa. Disarankan meningkatkan porsi instrumen safe-haven (Emas fisik / Cash yield) sebesar 5-10%.");
  } else {
    resilience = "Rentan (Perlu Lindung Nilai)";
    recommendations.push("Portofolio terlalu terkonsentrasi pada aset berisiko tinggi tanpa bantalan lindung nilai yang cukup.");
    recommendations.push("Lakukan rebalancing segera dengan mengalihkan sebagian profit ke instrumen pasar uang atau emas.");
  }

  return {
    scenario_key: scenarioKey,
    scenario_name: scenario.name,
    scenario_description: scenario.description,
    initial_portfolio_value: Math.round(initialTotal),
    stressed_portfolio_value: Math.round(stressedTotal),
    total_loss_idr: Math.round(totalDelta),
    drawdown_percent: Number(drawdownPct.toFixed(2)),
    resilience_rating: resilience,
    safe_haven_buffer_idr: Math.round(safeHavenBuffer),
    worst_hit_assets: worstHit,
    holdings_breakdown: breakdown,
    strategic_recommendations: recommendations,
  };
};
